version: "3.4"

networks:
    frontend:
      driver: ${NETWORKS_DRIVER}
    backend:
      driver: ${NETWORKS_DRIVER}

services:

    db:
        image: mb_db:latest
        environment:
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        ports:
            - "3306:3306"

    app:
        image: "magicbatches:latest"
        restart: on-failure
        ports: 
            - "5000:5000"
        depends_on: 
            - db